// Generated by CoffeeScript 1.10.0
(function() {
  var App, Character, Combat, Dungeon, getTipWithCoordinates, global, init, options, plyer1,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  global = window;

  global.Key = (function() {
    function Key() {}

    Key.up = 38;

    Key.down = 40;

    Key.left = 37;

    Key.right = 39;

    Key.space = 32;

    return Key;

  })();

  global.Chip = (function() {
    function Chip() {}

    Chip.road = 1;

    Chip.wall = 2;

    Chip.player = 3;

    Chip.treasureChest = 4;

    Chip.enemy1 = 5;

    Chip.enemy2 = 6;

    Chip.enemy3 = 7;

    Chip.trap = 8;

    Chip.enemies = [Chip.enemy1, Chip.enemy2, Chip.enemy3];

    return Chip;

  })();

  getTipWithCoordinates = function(x, y) {
    return Chip.road;
  };

  Character = (function() {
    function Character(options) {
      this.bindEvent = bind(this.bindEvent, this);
      this.x = options.x || 0;
      this.y = options.y || 0;
      this.name = options.name || "no name";
      this.hp = options.hp || 20;
      this.attack = options.attack || 3;
      this.deffense = options.deffense || 1;
      window.addEventListener('keydown', this.bindEvent, true);
    }

    Character.prototype.bindEvent = function(e) {
      switch (e.keyCode) {
        case Key.up:
          this.moveUp(1);
          break;
        case Key.down:
          this.moveDown(1);
          break;
        case Key.left:
          this.moveLeft(1);
          break;
        case Key.right:
          this.moveRight(1);
          break;
        case Key.space:
          this.openMenu(1);
      }
      this.moveRight(1);
      return this.logStatus();
    };

    Character.prototype.moveUp = function(distance) {
      var toY;
      toY = this.y - distance;
      if (this.canToMove(this.x, toY)) {
        return this.y = toY;
      }
    };

    Character.prototype.moveDown = function(distance) {
      var toY;
      toY = this.y + distance;
      if (this.canToMove(this.x, toY)) {
        return this.y = toY;
      }
    };

    Character.prototype.moveLeft = function(distance) {
      var toX;
      toX = this.x - distance;
      if (this.canToMove(toX, this.y)) {
        return this.x = toX;
      }
    };

    Character.prototype.moveRight = function(distance) {
      var toX;
      toX = this.x + distance;
      if (this.canToMove(toX, this.y)) {
        return this.x = toX;
      }
    };

    Character.prototype.canToMove = function(x, y) {
      var tipNo;
      tipNo = getTipWithCoordinates(x, y);
      switch (tipNo) {
        case Chip.road:
          return true;
        default:
          return false;
      }
    };

    Character.prototype.isEvent = function(x, y) {
      var tipNo;
      tipNo = getTipWithCoordinates(x, y);
      switch (tipNo) {
        case Chip.treasureChest:
          searchObject(Chip.treasureChest);
      }
      if (this.enemies.indexOf(tipNo) === -1) {
        return attack();
      }
    };

    Character.prototype.attack = function() {
      return console.log("player attacks");
    };

    Character.prototype.searchObject = function(tipNo) {
      switch (tipNo) {
        case Chip.treasureChest:
          return console.log("open chest");
      }
    };

    Character.prototype.openMenu = function() {
      return console.log("openMenu");
    };

    Character.prototype.logStatus = function() {
      return console.log("name: " + this.name + "\nx: " + this.x + ", y: " + this.y + "\nhp: " + this.hp);
    };

    return Character;

  })();

  options = {
    name: "トルネコ",
    x: 1,
    y: 10
  };

  plyer1 = new Character(options);

  console.log("\('o')/");

  App = (function() {
    var canvasInit, printMap;

    function App() {
      this.canvas = document.getElementById('main');
      this.ctx = this.canvas.getContext('2d');
      this.dungeon = new Dungeon();
      canvasInit(this.canvas, this.ctx);
    }

    canvasInit = function(canvas, ctx) {
      canvas.width = 640;
      canvas.height = 640;
      ctx.fillStyle = 'rgb(192, 80, 77)';
      ctx.fillRect(0, 0, 640, 640);
      return ctx.fill();
    };

    App.prototype.loop = function() {
      var mapData;
      console.log("loop");
      mapData = this.dungeon.getMapData;
      console.log(mapData);
      return printMap(mapData);
    };

    printMap = function(mapData) {
      var j, len, results, x, y;
      results = [];
      for (j = 0, len = mapData.length; j < len; j++) {
        x = mapData[j];
        results.push((function() {
          var k, len1, results1;
          results1 = [];
          for (k = 0, len1 = x.length; k < len1; k++) {
            y = x[k];
            results1.push(console.log('map' + mapData[x][y]));
          }
          return results1;
        })());
      }
      return results;
    };

    App.prototype.printWall = function() {};

    App.prototype.printRoad = function() {};

    App.prototype.printPlayer = function() {};

    App.prototype.printEnemy = function() {};

    return App;

  })();

  init = function() {
    window.rogue = new App();
    console.log("init");
    return window.rogue.loop();
  };

  window.addEventListener('load', init);

  Combat = (function() {
    function Combat() {}

    return Combat;

  })();

  Dungeon = (function() {
    function Dungeon(size) {
      this.size = size;
      this.init();
    }

    Dungeon.prototype.init = function() {
      var j, k, ref, ref1, results, results1, widthArray;
      widthArray = (function() {
        results = [];
        for (var j = 1, ref = this.size; 1 <= ref ? j <= ref : j >= ref; 1 <= ref ? j++ : j--){ results.push(j); }
        return results;
      }).apply(this).map(function(i) {
        return Chip.wall;
      });
      return this.dungeonArray = (function() {
        results1 = [];
        for (var k = 1, ref1 = this.size; 1 <= ref1 ? k <= ref1 : k >= ref1; 1 <= ref1 ? k++ : k--){ results1.push(k); }
        return results1;
      }).apply(this).map(function(i) {
        return widthArray;
      });
    };

    Dungeon.prototype.getChip = function(x, y) {
      return this.dungeonArray[x][y];
    };

    return Dungeon;

  })();

  console.log(new Dungeon(64).getChip(1, 1));

}).call(this);
