// Generated by CoffeeScript 1.10.0
(function() {
  var App, Character, Combat, Dungeon, Point, dungeon, getTipWithCoordinates, global, init, options, plyer1,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  global = window;

  global.Key = (function() {
    function Key() {}

    Key.up = 38;

    Key.down = 40;

    Key.left = 37;

    Key.right = 39;

    Key.space = 32;

    return Key;

  })();

  global.Chip = (function() {
    function Chip() {}

    Chip.road = 1;

    Chip.wall = 2;

    Chip.player = 3;

    Chip.treasureChest = 4;

    Chip.enemy1 = 5;

    Chip.enemy2 = 6;

    Chip.enemy3 = 7;

    Chip.trap = 8;

    Chip.enemies = [Chip.enemy1, Chip.enemy2, Chip.enemy3];

    return Chip;

  })();

  Point = (function() {
    function Point(x, y) {
      this.x = x || 0;
      this.y = y || 0;
    }

    return Point;

  })();

  getTipWithCoordinates = function(x, y) {
    return Chip.road;
  };

  Character = (function() {
    function Character(options) {
      this.bindEvent = bind(this.bindEvent, this);
      this.point = options.point || new Point(0, 0);
      this.name = options.name || "no name";
      this.hp = options.hp || 20;
      this.attack = options.attack || 3;
      this.deffense = options.deffense || 1;
      window.addEventListener('keydown', this.bindEvent, true);
    }

    Character.prototype.bindEvent = function(e) {
      switch (e.keyCode) {
        case Key.up:
          this.moveUp(1);
          break;
        case Key.down:
          this.moveDown(1);
          break;
        case Key.left:
          this.moveLeft(1);
          break;
        case Key.right:
          this.moveRight(1);
          break;
        case Key.space:
          this.openMenu(1);
      }
      return this.logStatus();
    };

    Character.prototype.moveUp = function(distance) {
      var toY;
      toY = this.point.y - distance;
      if (this.canToMove(this.point.x, toY)) {
        return this.point.y = toY;
      }
    };

    Character.prototype.moveDown = function(distance) {
      var toY;
      toY = this.point.y + distance;
      if (this.canToMove(this.point.x, toY)) {
        return this.point.y = toY;
      }
    };

    Character.prototype.moveLeft = function(distance) {
      var toX;
      toX = this.point.x - distance;
      if (this.canToMove(toX, this.point.x)) {
        return this.point.x = toX;
      }
    };

    Character.prototype.moveRight = function(distance) {
      var toX;
      toX = this.point.x + distance;
      if (this.canToMove(toX, this.point.x)) {
        return this.point.x = toX;
      }
    };

    Character.prototype.canToMove = function(point) {
      var tipNo;
      tipNo = getTipWithCoordinates(point.x, point.y);
      switch (tipNo) {
        case Chip.road:
          return true;
        default:
          return false;
      }
    };

    Character.prototype.isEvent = function(point) {
      var tipNo;
      tipNo = getTipWithCoordinates(point.x, point.y);
      switch (tipNo) {
        case Chip.treasureChest:
          searchObject(Chip.treasureChest);
      }
      if (this.enemies.indexOf(tipNo) === -1) {
        return attack();
      }
    };

    Character.prototype.attack = function() {
      return console.log("player attacks");
    };

    Character.prototype.searchObject = function(tipNo) {
      switch (tipNo) {
        case Chip.treasureChest:
          return console.log("open chest");
      }
    };

    Character.prototype.getAroundPoints = function() {
      var centerX, centerY, columnPoints, downY, j, k, leftX, len, len1, rightX, rowPoints, upY, x, xList, y, yList;
      leftX = this.point.x - 1;
      centerX = this.point.x;
      rightX = this.point.x + 1;
      xList = [leftX, centerX, rightX];
      upY = this.point.y - 1;
      centerY = this.point.y;
      downY = this.point.y + 1;
      yList = [upY, centerY, downY];
      columnPoints = [];
      for (j = 0, len = yList.length; j < len; j++) {
        y = yList[j];
        rowPoints = [];
        for (k = 0, len1 = xList.length; k < len1; k++) {
          x = xList[k];
          rowPoints.push({
            x: x,
            y: y
          });
        }
        columnPoints.push(rowPoints);
      }
      return columnPoints;
    };

    Character.prototype.openMenu = function() {
      return console.log("openMenu");
    };

    Character.prototype.logStatus = function() {
      return console.log("name: " + this.name + "\nx: " + this.point.x + ", y: " + this.point.y + "\nhp: " + this.hp);
    };

    return Character;

  })();

  options = {
    name: "トルネコ",
    point: new Point(1, 10)
  };

  plyer1 = new Character(options);

  console.log("\('o')/");

  App = (function() {
    var canvasInit;

    function App() {
      this.canvas = document.getElementById('main');
      this.ctx = this.canvas.getContext('2d');
      canvasInit(this.canvas, this.ctx);
    }

    canvasInit = function(canvas, ctx) {
      canvas.width = 500;
      canvas.height = 500;
      ctx.fillStyle = 'rgb(192, 80, 77)';
      ctx.fillRect(0, 0, 500, 500);
      return ctx.fill();
    };

    return App;

  })();

  init = function() {
    window.rogue = new App();
    return console.log("init");
  };

  window.addEventListener('load', init);

  Combat = (function() {
    function Combat() {}

    return Combat;

  })();

  Dungeon = (function() {
    function Dungeon(size) {
      this.size = size;
      this.init();
    }

    Dungeon.prototype.init = function() {
      var j, k, ref, ref1, results, results1, widthArray;
      widthArray = (function() {
        results = [];
        for (var j = 1, ref = this.size; 1 <= ref ? j <= ref : j >= ref; 1 <= ref ? j++ : j--){ results.push(j); }
        return results;
      }).apply(this).map(function(i) {
        return Chip.wall;
      });
      return this.mapData = (function() {
        results1 = [];
        for (var k = 1, ref1 = this.size; 1 <= ref1 ? k <= ref1 : k >= ref1; 1 <= ref1 ? k++ : k--){ results1.push(k); }
        return results1;
      }).apply(this).map(function(i) {
        return widthArray;
      });
    };

    Dungeon.prototype.getChip = function(x, y) {
      return this.dungeonArray[x][y];
    };

    Dungeon.prototype.getMapData = function() {
      return this.mapData;
    };

    return Dungeon;

  })();

  dungeon = new Dungeon(64);

  console.log(dungeon.getMapData());

}).call(this);
